provider: cloudflare

cloudflare:
  secretName: cloudflare-api-token
  proxied: false

sources:
  - service
  - ingress

domainFilters:
  - vidrochka.xyz

policy: sync

interval: 1m

logLevel: debug

rbac:
  create: true

serviceAccount:
  create: true

resources:
  requests:
    cpu: 25m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 250Mi
