apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: '1.16.1'
    helm:
      values: |
        provider: cloudflare
        # cloudflare:
        #   apiTokenSecretRef:
        #     name: cloudflare-api-token
        #     key: CF_API_TOKEN
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: CF_API_TOKEN
        policy: sync
        txtOwnerId: external-dns
        domainFilters:
          - "vidrochka.xyz"
        sources:
          - ingress
    # helm:
    #   valueFiles:
    #     - '/apps/external-dns/values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
